### PR TITLE
Fix #11 song names

### LINKED ISSUE #11: Feat song bug
When a song has someone else featured, the song is marked as wrong even if it is right.
maybe split the song before and after the feat, if it has feat in it and the part of the list with the index 0 is the song name (remember about the brackets)

### PR DESCRIPTION
**Pull request by transcental**

### CODE REVIEW

**Comment by DillonB07** [comment]
This also adds Pillow as a dependency in `pyproject.toml` as it isn't there.

**Comment by DillonB07** [comment]
How do I setup the MongoDB database for testing?

**Comment by DillonB07** [comment]
This is not ready. I've not added anything to fix song names yet.

**Comment by VulcanWM** [comment]
> How do I setup the MongoDB database for testing? @VulcanWM

As in this database or any random one?
Also I could give you edit access in the repl instead (I haven’t got the hang of GitHub yet lol)

**Comment by DillonB07** [comment]
I was going to setup any database just so I could use the website for testing. It doesn't really matter if it is the real one or a different one as long as the website works.

Sure, ok.

**Comment by VulcanWM** [comment]
Cool here’s the invite link: https://replit.com/join/khawxcytyg-vulcanwm

**Comment by DillonB07** [comment]
Thanks. Might want to delete that though.

**Comment by DillonB07** [comment]
Editing messages doesn't delete it. You can see the previous versions.

**Pull request merged**
